In [1]:
# Import the random module.
import random

In [12]:
random.random()

0.6958930827543398

In [13]:
random.randint(-90, 90)

73

In [14]:
random.random()

0.13905684826237985

In [17]:
random_number = random.randint(-90, 89) + random.random()
random_number

31.5529758342081

In [20]:
x = 1
latitudes = []
while x < 11:
    random_lat = random.randint(-90, 89) + random.random()
    latitudes.append(random_lat)
    x += 1

In [21]:
random.randrange(-90, 90, step=3)

27

In [22]:
random.uniform(-90, 90)

-33.42208037631941

In [23]:
# Import the NumPy module.
import numpy as np

In [24]:
np.random.uniform(-90.000, 90.000)

12.615850491279673

In [25]:
np.random.uniform(low=-90, high=90, size=50)

array([-58.05969455, -59.64631824, -38.19537702, -48.89505483,
         6.06763992,  10.69746043, -25.47754339,  46.5890898 ,
       -42.74720416,  45.19193576,  -2.05791448, -40.94413002,
        18.21222196,  81.8810683 ,  25.74007709,  18.66011129,
        76.1605162 ,  18.68930691, -64.75073091,  56.05627766,
        22.32178225, -45.65739462,  19.15252804, -22.40119038,
        49.30403888,  47.85998754,   3.83770705,  77.01832921,
        37.66172471, -32.30453558,  31.96252917, -87.77624442,
        70.1695295 ,  11.84968269,  74.12912952,  31.80981748,
       -66.93058971,  22.26454027,  40.7375718 ,  21.25878609,
       -17.59623822,  88.65691355, -63.49538979, -10.79862095,
       -29.29242819,  67.71194427,  11.72548718,  62.68026912,
        41.8804475 ,  43.70309566])

In [26]:
np.random.uniform(-90.000, 90.000, size=50)

array([ 7.16027301e+01,  5.96476465e+01, -5.79948903e+01,  3.03660093e+01,
       -6.30418485e+01,  4.40465468e+01,  8.55812451e+01,  3.92308406e+01,
       -1.92805679e+01, -3.37335082e+00,  7.38258818e+01,  6.40388049e+01,
        2.97939350e+01, -4.68708101e+01,  3.77297342e+00,  6.32145086e+01,
       -6.12833786e+01,  5.92165389e+01,  4.14060520e+01, -7.47016641e+01,
       -4.18713036e+01, -2.17711384e+01, -4.21459890e+01, -5.93657352e+01,
       -8.26018715e+01, -7.61137190e-02, -5.58109637e+01, -8.23179194e+01,
        3.42780406e+01, -4.35462479e+01, -5.88692144e+01, -8.45820773e+01,
       -2.87770539e+01, -6.55568449e+01,  5.92003974e+01, -3.09918369e+01,
        6.87239507e+00, -3.54634346e+01,  1.44745659e+01, -4.91048110e+01,
       -5.67708265e+01,  4.07720928e+01, -6.00699359e+01,  5.65116420e+01,
        5.50454723e+01, -5.72804243e+00, -4.70149128e+01,  2.60153893e+01,
        1.80030139e+01, -7.64303964e+01])

In [27]:
# Import timeit.
import timeit

In [28]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 47.13741302,  18.64440333,  87.93861834, ..., -70.88734643,
        53.51704496,  -5.47650423])

In [31]:
%timeit np.random.uniform(-90.000, 90.000, size=1500)

15.5 µs ± 106 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
np.random.uniform(-90.000, 90.000, size=1500)

array([ 39.10501414,   4.83269216, -66.50071059, ..., -62.31311438,
       -26.10692844, -44.23806833])

In [33]:
def latitudes(size):
    latitudes = []
    x = 0
    while x < (size):
        random_lat = random.randint(-90, 90) + random.random()
        latitudes.append(random_lat)
        x += 1
    return latitudes
# Call the function with 1500.
%timeit latitudes(1500)

1.64 ms ± 13.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [34]:
import timeit


In [35]:
np.random.uniform(-90.000, 90.000, size=15000)

array([ 75.4866562 , -88.86655655, -16.75516845, ..., -62.16254951,
       -51.31059339, -58.70514714])